### ISSUE TITLE
High CPU load

### ISSUE THREAD

**Issue by Hunter23071985** [Zerogate309/Rainmeter-Skin_Hex-H#1]
Hey!
In Windows 10 and 11 the skin takes 6-15% of the CPU resources.
Could you fix this?
Sincerely.

**Comment by Zerogate309** [comment]
I startet with >40% Load! So 15% is a good rate...
No, seriously: This is nothing i can "fix"!
Every Skin is a seperate Instance of Rainmeter.
Rainmeter makes everything, i can only made config Files who say: 
load this Picture and show the worth of this Variable!
Refresh the Skin every ...Seconds.

You can press the CPU-Load under 5% if you refresh every Skin only every 2 Seconds.
But, for a VU-Meter who gets updatet only every 2 Seconds...seriously?
Sincerly.

**Comment by Hunter23071985** [comment]
"> I startet with> 40% Load! ... This is nothing i can" fix "!
If you're able to reduce 40 to 15%, I hope you can continue. ))
If "Every Skin is a seperate Instance of Rainmeter", then you can:
1. Reduce consumption of instances.
For example, collect all variables into 1 skin, which writes data to the registry/txt, and the rest only read this data.
2. Reduce number of instances.
For example, allow to combine skins into "clusters".
3. Your version here...
