### ISSUE TITLE
Number of active processes

### ISSUE THREAD

**Issue by Hunter23071985** [Zerogate309/Rainmeter-Skin_Hex-H#3]
Hey!
Couldn't find a tile showing the number of active processes and services.
Can you add it?
Sincerely.

**Comment by Zerogate309** [comment]
I don't have this function!
For me is the number of active processes not importand, and there are barely not manny Skins that have this function!
But it would be possible to integrate it.
If you wanna see the Name of the processes...remember, my Skins are very small!
Sincerely.

**Comment by Hunter23071985** [comment]
'' > not manny Skins that have this function ... my Skins are very small!
I know several [skins](https://forum.rainmeter.net/viewtopic.php?t=27905) that show 1-10 top processes, ordered by CPU/GPU/RAM/IO utilization and it's small.
'' > not importand ... possible to integrate it.
It can be important to others, we wait you. ))
