### ISSUE TITLE
Interface translation

### ISSUE THREAD

**Issue by Hunter23071985** [Zerogate309/Rainmeter-Skin_Hex-H#4]
Hey!
The skin is great, but the interface is only in English.
Do you plan to translate into other languages?
I could help with Russian language, for example.
Sincerely.

**Comment by Zerogate309** [comment]
My first Idea was, to translate it in German and French. But German Language is to intricate for those small Skins.
And i don't speak French! Also i don't know if Russian fits. I should ask my Russian peers...
Maybe the "on-mouse-over"-Text...but i think, this is much work!
Sincerely.

**Comment by Hunter23071985** [comment]
" > I should ask my Russian peers
Give a list of variables and I'll try to make a short, close-to-meaning translation.
